name: workflow
on: [push]
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v1
      - name: Prepare environment
        run: npm ci
      - name: Lint
        uses: mooyoul/tslint-actions@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '*.ts'